apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app-db
  template:
    metadata:
      labels:
        app: springboot-app-db
    spec:
      containers:
        - name: springboot-app-db
          image: rajshivaram7/springboot-app-db
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SPRING_DATASOURCE_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  SPRING_DATASOURCE_URL: <base64-encoded-url>
  SPRING_DATASOURCE_USERNAME: <base64-encoded-username>
  SPRING_DATASOURCE_PASSWORD: <base64-encoded-password>